- name: mongodb installation
  hosts: all
  become: true
  tasks:
    - name: copy mongo repo
      ansible.builtin.copy: 
        src: mongo.repo
        dest: /etc/yum.repos.d/
    - name: install mongodb
      ansible.builtin.dnf:
        name: mongodb-org
        state: installed
    - name: replace listening adress for mongo
      ansible.builtin.replace: 
        path: /etc/mongod.conf
        regexp: 127.0.0.1
        replace: 0.0.0.0
    - name: start mongo service 
      ansible.builtin.systemd:
        name: mongod
        state: restarted
        enabled: yes